### PR TITLE
Fix name and source link

### PR DESCRIPTION
**Pull request by suhlig**
This probably was a left-over from Solarized.

### CODE REVIEW

**Comment by vcavallo** [comment]
Great, thanks!

**Comment by suhlig** [comment]
By the way, thank you for creating and maintaining this project! I was pleasantly surprised to see that I don't have to port @hukl's colors to the Gnome terminal myself (which I would probably not have been able to, anyway).

Now let's hope @hukl accepts [my proposal](https://github.com/hukl/Smyck-Color-Scheme/issues/31) to re-organize the contributions, and more people will be able to find this and similar repos.

**Comment by vcavallo** [comment]
@suhlig how _did_ you find my project, anyway? :)

**Comment by suhlig** [comment]
Do you really want me to [google that for you](https://google.com/search?q=gnome+terminal+smyck)? ;-)

**Pull request merged**
